#pragma once
#include "CoreMinimal.h"
#include "BUTTON_GUIDE_TYPE.generated.h"

UENUM(BlueprintType)
enum BUTTON_GUIDE_TYPE {
    BUTTON_GUIDE_OK,
    BUTTON_GUIDE_CANCEL,
    BUTTON_GUIDE_FACEBUTTON_BOTTOM,
    BUTTON_GUIDE_FACEBUTTON_RIGHT,
    BUTTON_GUIDE_FACEBUTTON_LEFT,
    BUTTON_GUIDE_FACEBUTTON_TOP,
    BUTTON_GUIDE_DPAD,
    BUTTON_GUIDE_DPAD_UP,
    BUTTON_GUIDE_DPAD_DOWN,
    BUTTON_GUIDE_DPAD_RIGHT,
    BUTTON_GUIDE_DPAD_LEFT,
    BUTTON_GUIDE_DPAD_LEFT_RIGHT,
    BUTTON_GUIDE_DPAD_UP_DOWN,
    BUTTON_GUIDE_LEFTSTICK,
    BUTTON_GUIDE_LEFTSTICK_UP,
    BUTTON_GUIDE_LEFTSTICK_DOWN,
    BUTTON_GUIDE_LEFTSTICK_RIGHT,
    BUTTON_GUIDE_LEFTSTICK_LEFT,
    BUTTON_GUIDE_RIGHTSTICK,
    BUTTON_GUIDE_RIGHTSTICK_UP,
    BUTTON_GUIDE_RIGHTSTICK_DOWN,
    BUTTON_GUIDE_RIGHTSTICK_RIGHT,
    BUTTON_GUIDE_RIGHTSTICK_LEFT,
    BUTTON_GUIDE_LEFT_SHOULDER,
    BUTTON_GUIDE_RIGHT_SHOULDER,
    BUTTON_GUIDE_LEFT_TRIGGER,
    BUTTON_GUIDE_RIGHT_TRIGGER,
    BUTTON_GUIDE_SPECIAL_RIGHT,
    BUTTON_GUIDE_SPECIAL_LEFT,
    BUTTON_GUIDE_MAX UMETA(Hidden),
};

