#pragma once
#include "CoreMinimal.h"
#include "EBtlMesEffectType.generated.h"

UENUM(BlueprintType)
enum class EBtlMesEffectType : uint8 {
    HpRecovery,
    HpSteal,
    SpRecovery,
    SpSteal,
    RecoveryNum,
    Bleeding = 0x0,
    Burn,
    Faint,
    SeriousFaint,
    Paralysis,
    Confuse,
    Frozen,
    Sleep,
    Poison,
    Charm,
    Dazzle,
    SuperFrozen,
    UnFightable,
    UnFightableEnemy,
    AilmentAll,
    AilmentNum,
    HpRegenerate = 0x0,
    SpRegenerate,
    Attack,
    Defense,
    Luck,
    CriticalRate,
    Avoid,
    ResistStrike,
    ResistSlash,
    ResistThrust,
    ResistBullet,
    ResistFire,
    ResistFreeze,
    ResistElectric,
    ResistAllAtk,
    ResistSleep,
    ResistFaint,
    ResistParalysis,
    ResistPoison,
    ResistConfuse,
    ResistCharm,
    ResistDazzle,
    DefinitelyCriticalHit,
    ResistJoke,
    ResistAllAilment,
    ResistAll,
    InvalidAllAilment,
    BufftDebuffNum,
    GearSecond = 0x0,
    Mirage,
    MonsterPoint,
    SukillEffectNum,
    SuccessSteal = 0x0,
    FailureSteal,
    NotExistStealItem,
    AvoidAttack,
    KickOutSuccess,
    KickOutFailure,
    CantAttackByHarem,
    TurnSkip,
    GroupMoved,
    AttackCharge,
    MWDown,
    LuckyAvoid,
    ActionResultNum,
    TreasureGetChance = 0x0,
    FoodGetChance,
    PowerCharge,
    SituationNum,
    MaxNum = 0x40,
    None,
};

