#pragma once
#include "CoreMinimal.h"
#include "EBTL_NEW_TUTORIAL_ID.generated.h"

UENUM(BlueprintType)
enum class EBTL_NEW_TUTORIAL_ID : uint8 {
    BTLNT_BTL1_TURN_PL1,
    BTLNT_BTL1_TURN_EN1_1,
    BTLNT_BTL1_TURN_EN1_2,
    BTLNT_BTL2_TURN_PL1,
    BTLNT_BTL3_TURN_PL1_1,
    BTLNT_BTL3_TURN_PL1_2,
    BTLNT_BTL4_TURN_PL1,
    BTLNT_BTL4_TURN_PL2,
    BTLNT_BTL5_TURN_PL1,
    BTLNT_BTL5_TURN_PL3,
    BTLNT_WHEN_TACTICAL,
    BTLNT_WHEN_ILL,
    BTLNT_WHEN_AVAILKARTS,
    BTLNT_RESISTWEAK,
    BTLNT_STRONG,
    BTLNT_BLOW,
    BTLNT_CAPTAINORDER,
    BTLNT_ALTERNATE,
    BTLNT_RANGE,
    BTLNT_ENTANGLE,
    BTLNT_WEAKRESIST2,
    BTLNT_LEVELUP,
    BTLNT_UNFIGHTABLE,
    BTLNT_ORDER_OF_ACTION,
    BTLNT_MAX UMETA(Hidden),
};

