#pragma once
#include "CoreMinimal.h"
#include "EBTL_NEW_TUTORIAL_PHASE_ID.generated.h"

UENUM(BlueprintType)
enum class EBTL_NEW_TUTORIAL_PHASE_ID : uint8 {
    BTLNTP_BTL_NONE,
    BTLNTP_BTL1_PRE,
    BTLNTP_BTL1_TURN_PL1,
    BTLNTP_BTL1_TURN_EN1,
    BTLNTP_BTL1_END,
    BTLNTP_BTL2_PRE,
    BTLNTP_BTL2_TURN_PL1,
    BTLNTP_BTL2_END,
    BTLNTP_BTL3_PRE,
    BTLNTP_BTL3_TURN_PL1,
    BTLNTP_BTL3_TURN_PL2,
    BTLNTP_BTL3_END,
    BTLNTP_BTL4_PRE,
    BTLNTP_BTL4_TURN_PL1,
    BTLNTP_BTL4_END,
    BTLNTP_BTL5_PRE,
    BTLNTP_BTL5_TURN_PL1,
    BTLNTP_BTL5_TURN_P1POST,
    BTLNTP_BTL5_TURN_PL2,
    BTLNTP_BTL5_TURN_PL3,
    BTLNTP_D003_010_PRE,
    BTLNTP_MAX UMETA(Hidden),
};

