#pragma once
#include "CoreMinimal.h"
#include "WIDGET_COLOR_TYPE.generated.h"

UENUM(BlueprintType)
enum class WIDGET_COLOR_TYPE : uint8 {
    ACCESSORY_BASE_HP,
    ACCESSORY_BASE_TP,
    ACCESSORY_BASE_ATK,
    ACCESSORY_BASE_DEF,
    ACCESSORY_BASE_MOVE,
    ACCESSORY_BASE_ITEM_DISTANCE,
    ACCESSORY_BASE_FIRE,
    ACCESSORY_BASE_FREEZE,
    ACCESSORY_BASE_LIGHTNING,
    ACCESSORY_BASE_SLASH,
    ACCESSORY_BASE_BULLET,
    ACCESSORY_BORDER_HP,
    ACCESSORY_BORDER_TP,
    ACCESSORY_BORDER_ATK,
    ACCESSORY_BORDER_DEF,
    ACCESSORY_BORDER_MOVE,
    ACCESSORY_BORDER_ITEM_DISTANCE,
    ACCESSORY_BORDER_FIRE,
    ACCESSORY_BORDER_FREEZE,
    ACCESSORY_BORDER_LIGHTNING,
    ACCESSORY_BORDER_SLASH,
    ACCESSORY_BORDER_BULLET,
    EXP_MENU_STATUS_UP,
    EXP_MENU_STATUS_ADD,
    WIDGET_COLOR_MAX UMETA(Hidden),
};

